nstudio/nativescript-audio

src/android/player.ts
src/ios/player.ts

* Implement completion and error callbacks on iOS. There is no good equivalent of info callbacks on iOS, so that callback is never called on iOS in this implementation. 
* Ensure that callbacks are optional on Android (as documented). This was causing a crash.
* Keep error and info callbacks from causing a crash due to incorrect return value. This was causing a crash.

Fix callbacks on iOS and Android

---

src/android/player.ts

Quick and easy, use the passed in file name verbatim if it isn't relative to ~/.

Allow playing from absolute paths in playFromFile on Android.

---

src/ios/recorder.ts

I’ve added two iOS functions that help a user detect what’s happening
with sound in real time.
isRecording is simple enough, returns true or false
getMeters will return the current level of volume being recorded in dB

Add iOS Recording Functionality To Get Volume Levels

---

.gitignore
.npmignore
demo/package.json
index.d.ts
package.json
src/ios/player.ts
src/ios/recorder.ts
tsconfig.json

Tons of good stuff. Clears up `not a module` TS issue consumers would encounter using this plugin. Also fixes typings issues locally when running demo. And a semantic issue bug with recorder 👍 
Fixing TS one PR at a time.

chore: fix typings issues

---

demo/app/main-view-model.ts
demo/package.json
package.json
src/ios/player.ts
src/ios/recorder.ts
tsconfig.json

https://github.com/bradmartin/nativescript-audio/issues/18

fix: ts issues during build

---

src/android/recorder.ts

I wanted to record `VOICE_COMMUNICATION` in https://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html#VOICE_COMMUNICATION

Allow to override default audioSource in Android

---

.gitignore
README.md
demo/app/main-view-model.ts
demo/package.json
demo/tsconfig.json
package.json
references.d.ts
tsconfig.json

In this PR:
- Plugin updated to build against `tns-core-modules@3.x.x` and `tns-platform-de
clarations@3.x.x`.
- Demo project updated to NativeScript 3.0
_Note_: 🎉   Plugin is still compatible with NativeScript 2.x - no changes in the code 🎉

NativeScript 3.0 update

---

src/ios/player.ts

Here audio will be routed to Speaker if only the current route type is Receiver (Ear Speaker). It won't route for other types. This will be better than previous solution.

 Audio routing to Speaker if from Receiver only 

---

src/android/player.ts

Getting several of these in my crash reporter. Since the `volume` setter is already type-safe and removes the need to pass the value redundantly, this also makes it cleaner.
```
Exception com.tns.NativeScriptException: Calling js method onAudioFocusChange failed TypeError: Cannot read property 'setVolume' of undefined File: "<embedded>, line: 36, column: 2103308 StackTrace: Frame: function:'onAudioFocusChange', file:'<embedded>', line: 36, column: 2103309
com.tns.Runtime.callJSMethodNative (Runtime.java)
com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1088)
com.tns.Runtime.callJSMethodImpl (Runtime.java:970)
com.tns.Runtime.callJSMethod (Runtime.java:957)
com.tns.Runtime.callJSMethod (Runtime.java:941)
com.tns.Runtime.callJSMethod (Runtime.java:933) …
```

TypeError: Cannot read property 'setVolume' of undefined

---

src/ios/player.ts
src/package.json

In existing version of plugin if you have system music playing (e.g. Music app or Spotify), the music will stop once you start playing a sound, and won't resume after the sound finished playing - unless you manually resume it in the music app.
I added the category option [AVAudioSessionCategoryOptions.DuckOthers](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionduckothers?language=objc) to the AVAudioSession to allow the music volume to be temporarily decreased while the sound plays, and return to normal once the sound finishes playing. 
I also had to deactivate the audio session in the dispose method to get this to work properly.

added ios .DuckOthers category option and deactivate session on dispose

---

README.md
src/android/player.ts
src/index.d.ts
src/options.ts
src/package.json

Everytime we instantiate TNSPlayer() it was requesting the audio focus and not abandoning it (until we call `dispose()` which is not always what we want). This is not recommended according to Android documentation and introduces a bug since this is not the expected behaviour.
Those issues are facing exactly this bug: #142 #137
Android docs states that a well-behaved audio app should manage audio focus according to these general guidelines:
> Call requestAudioFocus() immediately before starting to play and verify that the call returns AUDIOFOCUS_REQUEST_GRANTED. If you design your app as we describe in this guide, the call to requestAudioFocus() should be made in the onPlay() callback of your media session.
> When another app gains audio focus, stop or pause playing, or duck the volume …

Fix android audio focus management

---

src/android/player.ts
src/options.ts

This causes iOS to crash if AudioFocusDurationHint gets used (references android) because options.ts is not platform specific.

Moved AudioFocusDurationHint to android specific file.

---

src/android/player.ts

When the track completes, abandon the audio focus but don't release the
media player. This allows the track to be played again by calling
seekTo(0) and play(), like you can when running the plugin with iOS.
Previously trying to call methods such as seekTo or play after the track
completed resulted in {"player":{},"error":-38,"extra":0}. The only way
to play the track a second time was to call the init method again.

Android: Allow the track to be replayed

---

src/ios/player.ts

Previously when calling the play, pause or seekTo methods when running
on iOS and the player was not in the expected state, the Promise would
never be resolved.
e.g. this line would never complete if already in the playing state:
await player.play()

iOS: Resolve promises when calling play, pause or seekTo

---

src/android/player.ts

When running Android prior to Oreo, android.os.Build.VERSION_CODES.O
does not exist at runtime and so trying to use it produces an error.
Instead, use the API level number (26) directly.
The VERSION_CODES work in Java code because the compiler replaces them
with the numbers at build time, but that doesn't happen with JavaScript.

Android: To support older SDKs, don't use android.os.Build.VERSION_CODES

---

src/android/player.ts

To reproduce:
1. Start the track in the demo app.
2. Play a sound in another app. (I used the test sound in Google Maps.)
Notice that the demo app ducks the volume of the playing track.
3. Go back to the demo app. Pause and resume the track.
4. Play a sound in another app again.
Bug: This time the demo app doesn't change the volume of the track.
Fixed by retaining the _mOnAudioFocusChangeListener when pausing so that
it can be used when resuming again.

Android: Fix ducking after track paused on pre-Oreo Android devices

---

src/android/player.ts

Previously audio focus was requested by the playFromFile method, which
is called during initFromFile and initFromUrl. Getting audio focus this
early means that when an AUDIOFOCUS_GAIN event is received, the track
will start playing even though the caller never requested it to play.
Now the audio focus is not requested until playing the track.
Fixes #111

Android: Don't request audio focus on init

---

src/android/player.ts
src/index.d.ts
src/ios/player.ts

Introduce AudioFocusManager on android that will manage focus.
When audioMixing is true, player will use a global AudioFocusManager
If the developer doesn't want to handle focus at all, they just need to do `player.setAudioFocusManager(null);`
This allows for a single instance of focusRequest that will request focus at start and keeps track of when it needs to abandon focus

feat(android): better focus management between multiple players

---

README.md
src/android/recorder.ts
src/ios/recorder.ts
src/options.ts
src/package.json

Adds option details to readme
Adds `iosAudioQuality` which you can use to specific the AVAudioQuality enum.
Respects sampleRate on iOS

respects options in ios and adds one for AVAudioQuality

---

README.md

I have changed to the assets folder because with the folder that was there before it did not work by default, now it does, it seemed that the plugin did not work

chore(readme): fixed default file folder
